<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>srt</string>
	</array>
	<key>name</key>
	<string>SRT Subtitles</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>A number indicating which subtitle it is in the sequence.</string>
			<key>match</key>
			<string>^(\d+)$</string>
			<key>name</key>
			<string>constant.numeric.sequence.srt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.srt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.srt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.srt</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>The time that the subtitle should appear on the screen, and then disappear.</string>
			<key>match</key>
			<string>^(\d{2}:\d{2}:\d{2},\d{3})(\s--&gt;\s)(\d{2}:\d{2}:\d{2},\d{3})$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;(b)\&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.srt</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;b&gt;Bold&lt;/b&gt;</string>
			<key>end</key>
			<string>\&lt;\/(b)\&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.srt</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.bold.srt</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;(i)\&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.srt</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;i&gt;Italic&lt;/i&gt;</string>
			<key>end</key>
			<string>\&lt;\/(i)\&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.srt</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.italic.srt</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;(u)\&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.srt</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;u&gt;Underline&lt;/u&gt;</string>
			<key>end</key>
			<string>\&lt;\/(u)\&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.srt</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.underline.srt</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Position tags</string>
			<key>match</key>
			<string>\{\\an[1-9]{1}\}</string>
			<key>name</key>
			<string>entity.name.function.srt</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.srt</string>
	<key>uuid</key>
	<string>54855958-b465-408a-baed-bc81a5ff3d09</string>
</dict>
</plist>
